  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module counter::counter_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::dapps_system;

  use dubhe::storage_migrate;

  use dubhe::dapps_schema::Dapps;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use counter::dapp_key::DappKey;

  use sui::dynamic_field as df;

  public struct Counter has key, store {
    id: UID,
  }

  public fun borrow_value(self: &Counter): &StorageValue<u32> {
    storage_migrate::borrow_field(&self.id, b"value")
  }

  public(package) fun borrow_mut_value(self: &mut Counter): &mut StorageValue<u32> {
    storage_migrate::borrow_mut_field(&mut self.id, b"value")
  }

  public(package) fun create(ctx: &mut TxContext): Counter {
    let mut id = object::new(ctx);
    storage_migrate::add_field<StorageValue<u32>>(&mut id, b"value", storage_value::new());
    Counter { id }
  }

  public fun migrate(_counter: &mut Counter, _cap: &UpgradeCap) {}

  // ======================================== View Functions ========================================

  public fun get_value(self: &Counter): Option<u32> {
    self.borrow_value().try_get()
  }

  // =========================================================================================================
}
