  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module counter::counter_event_increment {

  use sui::event;

  use std::ascii::String;

  public struct IncrementEvent has copy, drop {
    value: u32,
  }

  public fun new(value: u32): IncrementEvent {
    IncrementEvent {
                                   value
                               }
  }

  public fun emit(value: u32) {
    event::emit(IncrementEvent {
                                   value
                               });
  }
}
