  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::monster_catch_attempt_event {

  use sui::event;

  use std::ascii::String;

  use constantinople::encounter_monster_catch_result::MonsterCatchResult;

  use constantinople::encounter_monster_info::MonsterInfo;

  public struct MonsterCatchAttemptEvent has copy, drop {
    player: address,
    monster: address,
    result: MonsterCatchResult,
  }

  public fun new(player: address, monster: address, result: MonsterCatchResult): MonsterCatchAttemptEvent {
    MonsterCatchAttemptEvent {
                                   player,monster,result
                               }
  }

  public fun emit(player: address, monster: address, result: MonsterCatchResult) {
    event::emit(MonsterCatchAttemptEvent {
                                   player,monster,result
                               });
  }
}
